@startuml

|#lightgray|System|
start
:Display Staff list ;
|#White|Staff|
:Choose a staff ;
:Press button Update ;
|#lightgray|System|
:Prompts user to enter Staff information ;
|#White|Staff|
repeat
  :Enter new Staff information and submit ;
backward:Display an error message and prompt the user to re-enter the information;
repeat while (Check if the information is valid or not) is (INVALID)
-> VALID;
|#pink|DATABASE|
:Store new Staff's information in the database ; 
|#lightgray|System|
:Display the new Staff in the Staff list ;
stop

@enduml
